POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1yVW5jaGFpbmVkIiwiaWQiOiI2NGYwMGU2OWRkNzVjM2VhZjYxZDdmZjciLCJpYXQiOjE2OTM2NzM3MDUsImV4cCI6MTY5MzY3NzMwNX0._eZ-sXKPXfqwRdhLVjtoFyy9VoIkPMl2GW51BJyy-B4

{
    "title": "demonLord",
    "url": "blogs.com",
    "author": "biscuitOliva"
}